# Generated by Django 4.2.13 on 2024-07-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoproductstoreapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
