# Generated by Django 4.2.13 on 2024-07-16 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoproductstoreapi', '0002_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, default=0)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoproductstoreapi.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoproductstoreapi.user')),
            ],
        ),
    ]
