# Generated by Django 4.2.7 on 2024-07-31 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoproductstoreapi', '0007_cartproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='ecoproductstoreapi.cart'),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='ecoproductstoreapi.product'),
        ),
    ]
