# Generated by Django 4.2.13 on 2024-08-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoproductstoreapi', '0007_cartproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
